name: pyvisor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - pillow
  - matplotlib
  - pims
  - tqdm
  - ffmpeg
  - pyqt=5
  - pytest
  - pip:
      - pygame>=2.1.3
      - av>=10.0.0
      - dill
      - xlsxwriter
      - appdirs
 